title: Comparison Interface
remote_theme: HiddenHarmsHub/jekyll-theme-zendesk-garden@main
search_enabled: true
auto_page_title: true
sidebar:
    - index
    - installation
    - configuration
    - export-data
    - testing
    - commands
